
// export default [
//     { nome: 'O Poderoso Chefão', genero: 'Drama/Ação', ano: 1972 },
//     { nome: 'As Branquelas', genero: 'Comédia', ano: 2004 },
//     { nome: 'Sexta-feira 13', genero: 'Terror', ano: 1980 },
//     { nome: 'Matrix', genero: 'Ficção Científica/Ação', ano: 1999 },
//     { nome: 'Kung-fu Panda', genero: 'Animação', ano: 2008 },
// ];


const filmesMaisAssistidos = [
  { nome: "Avatar", genero: "Ficção Científica", ano: 2009 },
  { nome: "Vingadores: Ultimato", genero: "Ação/Aventura", ano: 2019 },
  { nome: "Avatar: O Caminho da Água", genero: "Ficção Científica", ano: 2022 },
  { nome: "Titanic", genero: "Romance/Drama", ano: 1997 },
  { nome: "Star Wars: Episódio VII - O Despertar da Força", genero: "Ficção Científica/Aventura", ano: 2015 },
  { nome: "Vingadores: Guerra Infinita", genero: "Ação/Aventura", ano: 2018 },
  { nome: "Jurassic World", genero: "Aventura/Ficção Científica", ano: 2015 },
  { nome: "O Rei Leão", genero: "Animação/Aventura", ano: 2019 },
  { nome: "The Avengers", genero: "Ação/Aventura", ano: 2012 },
  { nome: "Velozes e Furiosos 7", genero: "Ação/Thriller", ano: 2015 },
  { nome: "Frozen II", genero: "Animação/Aventura", ano: 2019 },
  { nome: "Jurassic World: Reino Ameaçado", genero: "Aventura/Ficção Científica", ano: 2018 },
  { nome: "Os Vingadores: Era de Ultron", genero: "Ação/Aventura", ano: 2015 },
  { nome: "Harry Potter e as Relíquias da Morte - Parte 2", genero: "Fantasia/Aventura", ano: 2011 },
  { nome: "Star Wars: Episódio VIII - Os Últimos Jedi", genero: "Ficção Científica/Aventura", ano: 2017 },
  { nome: "Jurassic Park", genero: "Aventura/Ficção Científica", ano: 1993 },
  { nome: "Frozen", genero: "Animação/Aventura", ano: 2013 },
  { nome: "Capitão Marvel", genero: "Ação/Ficção Científica", ano: 2019 },
  { nome: "Homem de Ferro 3", genero: "Ação/Ficção Científica", ano: 2013 },
  { nome: "Minions", genero: "Animação/Comédia", ano: 2015 },
  { nome: "Pantera Negra", genero: "Ação/Ficção Científica", ano: 2018 },
  { nome: "Star Wars: Episódio I - A Ameaça Fantasma", genero: "Ficção Científica/Aventura", ano: 1999 },
  { nome: "Toy Story 4", genero: "Animação/Aventura", ano: 2019 },
  { nome: "Transformers: O Lado Oculto da Lua", genero: "Ação/Ficção Científica", ano: 2011 },
  { nome: "Transformers: A Era da Extinção", genero: "Ação/Ficção Científica", ano: 2014 },
  { nome: "Alice no País das Maravilhas", genero: "Fantasia/Aventura", ano: 2010 },
  { nome: "Piratas do Caribe: O Baú da Morte", genero: "Aventura/Fantasia", ano: 2006 },
  { nome: "Alice Através do Espelho", genero: "Fantasia/Aventura", ano: 2016 },
  { nome: "Vingadores", genero: "Ação/Aventura", ano: 2012 },
  { nome: "Shrek 2", genero: "Animação/Comédia", ano: 2004 },
  { nome: "O Hobbit: A Desolação de Smaug", genero: "Fantasia/Aventura", ano: 2013 },
  { nome: "Deadpool 2", genero: "Ação/Comédia", ano: 2018 },
  { nome: "Procurando Dory", genero: "Animação/Aventura", ano: 2016 },
  { nome: "Batman: O Cavaleiro das Trevas", genero: "Ação/Crime", ano: 2008 },
  { nome: "Os Incríveis 2", genero: "Animação/Ação", ano: 2018 },
  { nome: "Capitão América: Guerra Civil", genero: "Ação/Ficção Científica", ano: 2016 },
  { nome: "Harry Potter e a Pedra Filosofal", genero: "Fantasia/Aventura", ano: 2001 },
  { nome: "Rogue One: Uma História Star Wars", genero: "Ficção Científica/Aventura", ano: 2016 },
  { nome: "Homem-Aranha: Longe de Casa", genero: "Ação/Aventura", ano: 2019 },
  { nome: "Moana", genero: "Animação/Aventura", ano: 2016 },
  { nome: "Piratas do Caribe: A Maldição do Pérola Negra", genero: "Aventura/Fantasia", ano: 2003 },
  { nome: "Liga da Justiça", genero: "Ação/Ficção Científica", ano: 2017 },
  { nome: "Transformers: O Reencontro dos Derrotados", genero: "Ação/Ficção Científica", ano: 2009 },
  { nome: "Cinquenta Tons de Cinza", genero: "Romance/Drama", ano: 2015 },
  { nome: "Homem-Formiga e a Vespa", genero: "Ação/Ficção Científica", ano: 2018 },
  { nome: "Toy Story 3", genero: "Animação/Aventura", ano: 2010 },
  { nome: "Coco", genero: "Animação/Aventura", ano: 2017 },
  { nome: "Velozes e Furiosos 8", genero: "Ação/Thriller", ano: 2017 }
];

export default filmesMaisAssistidos;